/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Utils.Role;
import Utils.Session;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;

public class GiaoDienChinhGUI extends javax.swing.JFrame {

    /**
     * Creates new form SinhVienGUI
     */
    public GiaoDienChinhGUI() {
        initComponents();
        customizeMenuForRole();
        CanGiua();
    }
  public void CanGiua(){
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        int frameWidth = getWidth();
        int frameHeight = getHeight();
        int x = (screenWidth - frameWidth) / 2;
        int y = (screenHeight - frameHeight) / 2;
        setLocation(x, y);
    }
    private void customizeMenuForRole() {
        // Check the current role and hide the appropriate menu items
        if (Session.currentRole == Role.ADMIN) {
            menuDangKy.setVisible(false); // Hide registration menu for staff
        } else if (Session.currentRole == Role.STUDENT) {
            menuSinhVien.setVisible(false); // Hide student menu for students
            menuMonHoc.setVisible(false);    // Hide subject menu for students
            menuNhapDiem.setVisible(false);  // Hide score entry menu for students
            jMenu2.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSinhVien = new javax.swing.JMenuItem();
        menuMonHoc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuDangKy = new javax.swing.JMenuItem();
        menuNhapDiem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(40, 42, 54));

        jMenu1.setText("Tùy chọn");

        jMenuItemThoat.setText("Thoát");
        jMenuItemThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemThoatActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý hệ thống");

        menuSinhVien.setText("Sinh viên");
        menuSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSinhVienActionPerformed(evt);
            }
        });
        jMenu2.add(menuSinhVien);

        menuMonHoc.setText("Môn học");
        menuMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMonHocActionPerformed(evt);
            }
        });
        jMenu2.add(menuMonHoc);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Nghiệp vụ");

        menuDangKy.setText("Đăng ký");
        menuDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangKyActionPerformed(evt);
            }
        });
        jMenu3.add(menuDangKy);

        menuNhapDiem.setText("Nhập điểm");
        menuNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhapDiemActionPerformed(evt);
            }
        });
        jMenu3.add(menuNhapDiem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemThoatActionPerformed
        // TODO add your handling code here:
        dispose();
        new DangNhapGUI().setVisible(true);
    }//GEN-LAST:event_jMenuItemThoatActionPerformed
    private SinhVienGUI sinhVienGUI;
    private void menuSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSinhVienActionPerformed
        // TODO add your handling code here:
        sinhVienGUI = new SinhVienGUI();
        this.sinhVienGUI.setVisible(true);
        this.jPanel2.setLayout(new FlowLayout());
        this.jPanel2.removeAll();
        this.jPanel2.add(sinhVienGUI, BorderLayout.CENTER);
        this.jPanel2.updateUI();

        // Cập nhật lại giao diện
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_menuSinhVienActionPerformed
    private MonHocGUI monHocGUI;
    private void menuMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMonHocActionPerformed

        // TODO add your handling code here:
        monHocGUI = new MonHocGUI();
        this.monHocGUI.setVisible(true);
        this.jPanel2.setLayout(new FlowLayout());
        this.jPanel2.removeAll();
        this.jPanel2.add(monHocGUI, BorderLayout.CENTER);
        this.jPanel2.updateUI();

        // Cập nhật lại giao diện
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_menuMonHocActionPerformed
    private DangKyGUI dangKyGUI;
    private void menuDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangKyActionPerformed
        // TODO add your handling code here:
        dangKyGUI = new DangKyGUI();
        this.dangKyGUI.setVisible(true);
        this.jPanel2.setLayout(new FlowLayout());
        this.jPanel2.removeAll();
        this.jPanel2.add(dangKyGUI, BorderLayout.CENTER);
        this.jPanel2.updateUI();

        // Cập nhật lại giao diện
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_menuDangKyActionPerformed
    private NhapDiemGUI nhapDiemGUI;
    private void menuNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhapDiemActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        nhapDiemGUI = new NhapDiemGUI();
        this.nhapDiemGUI.setVisible(true);
        this.jPanel2.setLayout(new FlowLayout());
        this.jPanel2.removeAll();
        this.jPanel2.add(nhapDiemGUI, BorderLayout.CENTER);
        this.jPanel2.updateUI();

        // Cập nhật lại giao diện
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_menuNhapDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinhGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemThoat;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menuDangKy;
    private javax.swing.JMenuItem menuMonHoc;
    private javax.swing.JMenuItem menuNhapDiem;
    private javax.swing.JMenuItem menuSinhVien;
    // End of variables declaration//GEN-END:variables
}
